### ISSUE TITLE
Getting syntax error while running beepboop

### ISSUE THREAD

**Issue by Jigenx** [Garlicvideos/reddits-nightmare#15]
Line:2
Char:1
Error:Syntax error
Code:800A03EA

Here's the first few lines from when I open beepboop on notepad

 //Initialise required libraries
const { IgApiClient, IgCheckpointError, IgLoginBadPasswordError, IgChallengeWrongCodeError } = require("instagram-private-api");
const ig = new IgApiClient();
const Bluebird = require("bluebird");
const fs = require("fs");
const request = require('request');

**Comment by Jigenx** [comment]
Also thats what I get when I run node beepboop.js

![image](https://user-images.githubusercontent.com/78457570/106690048-0ac7be00-659f-11eb-84c7-2ee276146d42.png)

**Comment by Axiver** [comment]
Hi there, I will need a little bit more information to assist you in resolving the first error you're getting.

May I know what program you were using to run the script in order to get

> Line:2
Char:1
Error:Syntax error
Code:800A03EA

As for the issue with setting your own custom caption, I did a little digging and it appears that the feature got lost when I added OCR in [release 1.2.1](https://github.com/Garlicvideos/reddits-nightmare/releases/tag/1.2.1).

I have pushed a new commit to master with a hotfix. The bot should now boot up properly, but the custom caption you set will not be used. You can download the latest version by clicking [here](https://github.com/Garlicvideos/reddits-nightmare/archive/master.zip).

I will be re-implementing the custom caption feature in the next release.

**Comment by Jigenx** [comment]
Hey the first program is beepboop javascript file that came with the bot file.

When I first ran the bot, it downloaded couple posts from the subreddit but never uploaded, when I tried to rerun I got the second error in the command prompt

> 
> ![image](https://user-images.githubusercontent.com/78457570/106690048-0ac7be00-659f-11eb-84c7-2ee276146d42.png)

So I tried to check beepboop, but got the first error



> Line:2
> Char:1
> Error:Syntax error
> Code:800A03EA
>

**Comment by Axiver** [comment]
Looks like you ran `beepboop.js` instead of `node beepboop.js` in order to get the first error.
Well then, if there's any other bug you're encountering, do let me know.
I will reference this issue and let you know once the next release comes out.
