### ISSUE TITLE
Can't find "npm i" in bot's directoy

### ISSUE THREAD

**Issue by ajohan97** [Garlicvideos/reddits-nightmare#16]
This is the popup I am getting

![error](https://user-images.githubusercontent.com/77068812/128265745-fb4a3ce6-d7d9-4c53-aab5-e847eacaa05b.PNG)

**Comment by Axiver** [comment]
You're getting that error because you're just trying to run the bot by double-clicking the file.

You need to first install Node.js together with NPM, then open up Command Prompt (CMD).

In CMD, `cd` to the directory your `beepboop.js` is located in (e.g. in this case it appears to be `C:\Users\Alex 2\Documents\reddits-nightmare-master\reddits-nightmare-master\bot\).

Then from there, run `npm i` which would install the required packages, and when its done, run `node beepboop.js`.

Please let me know how it goes. Thank you.

**Comment by Axiver** [comment]
As this thread has been inactive for well over a month now, I will be closing it. Feel free to re-open if this is still an issue you face.
