### ISSUE TITLE
not getting any auto comments or comments in general

### ISSUE THREAD

**Issue by C0d3Crush** [Garlicvideos/reddits-nightmare#17]
the pictures get uploaded but no caption at all.
i might have fucked it up. i copyed the original File from download. and did some changes to the beepbood thing.

**Comment by C0d3Crush** [comment]
but i reinstalled everything even node and did the whole setup again. still no comments

**Comment by Axiver** [comment]
Hi, do you mean captions?

The bot does not currently support auto-commenting on its own posts, but it should definitely be able to upload images with captions.

Otherwise, I just downloaded a fresh copy of the project and it ran perfectly fine for me.

To find out more, may I know what changes you made to the `beepboop.js` file? Also, you could try to download a new copy of the project and run through the automated setup.

**Comment by Axiver** [comment]
Due to inactivity, I will be closing this issue. Feel free to re-open it if the problem persists.
